name: Deploy Workers to Cloudflare

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
    
      - name: Deploy Twitch-Get-Status
        uses: cloudflare/wrangler-action@v3.1.0
        env: 
          ROUTE: ${{ secrets.CF_WORKER_ROUTE_TWITCH_GET_STATUS }}
        with:
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          apiToken: ${{ secrets.CF_API_TOKEN }}
          secrets: ROUTE
          
          workingDirectory: packages/workers/twitch-get-status
          command: deploy --route
