name: Deploy Workers to Cloudflare

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
    
      - name: Deploy twitch-status
        uses: cloudflare/wrangler-action@v3.1.0
        with:
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          apiToken: ${{ secrets.CF_API_TOKEN }}
          
          workingDirectory: packages/workers/twitch-status

      - name: Deploy twitch-eventsub-sched
        uses: cloudflare/wrangler-action@v3.1.0
        with:
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          apiToken: ${{ secrets.CF_API_TOKEN }}
          
          workingDirectory: packages/workers/twitch-eventsub-sched
